version: "3.9"

services:
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rentalx_db
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentalx
    ports:
      - 4000:4000
    volumes:
      - .:/usr/app
    links:
      - db
    depends_on: 
      - db     

volumes:
  pgdata:
    driver: local
